[theme]
#7792E3 273346
# Primary accent for interactive elements
primaryColor = '#3A5A40'
# Background color for the main content area
backgroundColor = '#EEECE8'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3A5A40'    

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
